import { useState, useEffect } from "react";
import { axiosInstance } from "../utils/axiosInstance";
import { supabase } from "../utils/supabaseClient";

export function useActivityOperations({
  tripId,
  actions,
  showNotification,
  currentParticipants = [],
  onPreferencesUpdate,
}) {
  const [refreshingActivity, setRefreshingActivity] = useState(null);
  const [lastUpdateTimestamp, setLastUpdateTimestamp] = useState(null);

  // Setup real-time updates channel
  useEffect(() => {
    if (!tripId) return;

    const channel = supabase
      .channel(`trip-${tripId}`)
      .on("broadcast", { event: "trip-update" }, ({ payload }) => {
        if (
          payload.tripId === tripId &&
          payload.timestamp !== lastUpdateTimestamp
        ) {
          // Determine appropriate message based on action type
          let updateMessage =
            "Trip has been updated by another user. Refreshing...";

          if (payload.action === "delete") {
            updateMessage =
              "An activity has been deleted by another user. Refreshing...";
          } else if (payload.action === "refresh") {
            updateMessage =
              "An activity has been regenerated by another user. Refreshing...";
          } else if (payload.action === "preferences-update") {
            updateMessage =
              "Trip preferences have been updated by another user. Refreshing...";
            // Notify parent component about preferences update
            if (onPreferencesUpdate) {
              onPreferencesUpdate(true);
            }
          } else if (payload.action === "preferences-update-start") {
            updateMessage =
              "Trip preferences are being updated by another user...";
            // Notify parent component about preferences update start
            if (onPreferencesUpdate) {
              onPreferencesUpdate(true);
            }
          }

          showNotification("info", updateMessage);

          // Set all activities to "refreshing" to trigger image refresh
          setRefreshingActivity("all-activities");

          // Only fetch new data if it's not a preferences-update-start event
          if (payload.action !== "preferences-update-start") {
            // Refetch the trip data
            axiosInstance
              .get(`/trips/${tripId}`)
              .then((response) => {
                if (response.data && response.data.response) {
                  actions.processItineraryData(response.data.response);
                  // Reset refreshing after data is processed
                  setTimeout(() => {
                    setRefreshingActivity(null);
                    if (
                      (payload.action === "preferences-update" ||
                        payload.action === "preferences-update-start") &&
                      onPreferencesUpdate
                    ) {
                      onPreferencesUpdate(false);
                    }
                  }, 1000);
                }
              })
              .catch((error) => console.error("Error refreshing trip:", error));
          }
        }
      })
      .subscribe();

    return () => {
      channel.unsubscribe();
    };
  }, [
    tripId,
    lastUpdateTimestamp,
    actions,
    showNotification,
    onPreferencesUpdate,
  ]);

  const handleRefreshActivity = async (activityId) => {
    setRefreshingActivity(activityId);
    try {
      showNotification("info", "Regenerating activity...");
      const response = await axiosInstance.post(
        `/trip/${tripId}/regenerate-activity`,
        {
          activityId: activityId,
        }
      );

      // Set a timestamp for this update
      const updateTimestamp = new Date().toISOString();
      setLastUpdateTimestamp(updateTimestamp);

      // Broadcast the update to other users
      await supabase.channel(`trip-${tripId}`).send({
        type: "broadcast",
        event: "trip-update",
        payload: {
          tripId: tripId,
          timestamp: updateTimestamp,
          action: "refresh",
          activityId: activityId,
        },
      });

      if (response.data.itinerary) {
        const newItineraryData = {
          response: {
            itinerary: response.data.itinerary,
            participants: currentParticipants,
          },
        };
        await actions.processItineraryData(newItineraryData);
        showNotification("success", "Activity regenerated successfully");
      } else {
        console.error("Invalid response structure:", response);
        showNotification(
          "error",
          "Failed to regenerate activity - invalid response from server"
        );
      }
    } catch (error) {
      console.error("Error refreshing activity:", error);
      showNotification(
        "error",
        "Failed to regenerate activity: " +
          (error.response?.data?.message || error.message)
      );
    } finally {
      setRefreshingActivity(null);
    }
  };

  const handleDeleteActivity = async (activityId) => {
    try {
      showNotification("info", "Deleting activity...");
      const response = await axiosInstance.delete(
        `/trip/${tripId}/activity/${activityId}`
      );

      // Set a timestamp for this update regardless of response format
      const updateTimestamp = new Date().toISOString();
      setLastUpdateTimestamp(updateTimestamp);

      // Broadcast the update to other users immediately
      await supabase.channel(`trip-${tripId}`).send({
        type: "broadcast",
        event: "trip-update",
        payload: {
          tripId: tripId,
          timestamp: updateTimestamp,
          action: "delete",
          activityId: activityId,
        },
      });

      let itineraryData = response.data.itinerary;
      if (response.data.response?.itinerary) {
        itineraryData = response.data.response.itinerary;
      } else if (response.data.data?.itinerary) {
        itineraryData = response.data.data.itinerary;
      } else if (response.data.itinerary) {
        itineraryData = response.data.itinerary;
      }

      if (itineraryData) {
        const newItineraryData = {
          response: {
            itinerary: itineraryData,
            participants: currentParticipants,
          },
        };
        await actions.processItineraryData(newItineraryData);
        showNotification("success", "Activity deleted successfully");
      } else {
        try {
          const tripResponse = await axiosInstance.get(`/trips/${tripId}`);
          if (tripResponse.data && tripResponse.data.response) {
            const data = tripResponse.data.response;
            if (data.itinerary.trip_type === "road") {
              actions.processRoadData(data);
            } else {
              actions.processItineraryData(data);
            }
            showNotification("success", "Activity deleted successfully");
          }
        } catch (reloadError) {
          console.error("Error reloading trip data:", reloadError);
          showNotification(
            "error",
            "Activity deleted but failed to update the view. Please refresh the page."
          );
        }
      }
    } catch (error) {
      console.error("Error deleting activity:", error);
      showNotification(
        "error",
        "Error deleting activity: " +
          (error.response?.data?.message || error.message)
      );
    }
  };

  return {
    refreshingActivity,
    handleRefreshActivity,
    handleDeleteActivity,
    lastUpdateTimestamp,
  };
}
